```{r}
library(ggplot2)
library(cowplot)
```

# COMPARATIVE & AGGREGATED

# Raw

## Empirical

### Raw

```{r}
AUC_Emp <- readRDS("Objects/AUC_EmpiricalData.rds")

par(mar = c(12, 4, 2, 2))
plot(1:10, AUC_Emp$AUC_data, type = "p", 
     main = "Empirical Data, All Populations", 
     xaxt = "none", xlab = "", ylim = c(0, 1), ylab = "AUC",
     col = "orchid", pch = 19, cex = 1)
abline(h = 0.5, lty = 3)
axis(side = 1, at = 1:10, labels = metrics_full, las = 2, cex.axis = 1)
```

```{r}
AUC_Emp_Ex5 <- readRDS("Objects/AUC_EmpiricalData_ExPop5.rds")

par(mar = c(12, 4, 2, 2))
plot(1:10, AUC_Emp_Ex5$AUC_data, type = "p", 
     main = "Empirical Data, Excluding Pop'n 5", 
     xaxt = "none", xlab = "", ylim = c(0, 1), ylab = "AUC",
     col = "orchid", pch = 19, cex = 1)
abline(h = 0.5, lty = 3)
axis(side = 1, at = 1:10, labels = metrics_full, las = 2, cex.axis = 1)
```

### Adjusted

```{r}
AUC_AdjEmp <- readRDS("Objects/AUC_AdjEmpiricalData.rds")

par(mar = c(12, 4, 2, 2))
plot(1:10, AUC_AdjEmp$AUC_data, type = "p", 
     main = "Adjusted Empirical Data, All Populations", 
     xaxt = "none", xlab = "", ylim = c(0, 1), ylab = "AUC",
     col = "orchid", pch = 19, cex = 1)
abline(h = 0.5, lty = 3)
axis(side = 1, at = 1:10, labels = metrics_full, las = 2, cex.axis = 1)
```

```{r}
AUC_AdjEmp_Ex5 <- readRDS("Objects/AUC_AdjEmpiricalData_ExPop5.rds")

par(mar = c(12, 4, 2, 2))
plot(1:10, AUC_AdjEmp_Ex5$AUC_data, type = "p", 
     main = "Adjusted Empirical Data, Excluding Pop'n 5", 
     xaxt = "none", xlab = "", ylim = c(0, 1), ylab = "AUC",
     col = "orchid", pch = 19, cex = 1)
abline(h = 0.5, lty = 3)
axis(side = 1, at = 1:10, labels = metrics_full, las = 2, cex.axis = 1)
```

## Simulated

```{r}
AUC_Sim <- readRDS("Objects/AUC_SimulatedData.rds")

par(mar = c(12, 4, 2, 2))
plot(1:10, AUC_Sim$AUC_5, type = "p", 
     main = "Simulated Data", 
     xaxt = "none", xlab = "", ylim = c(0, 1), ylab = "AUC",
     col = alpha("red3", 0.75), pch = 19, cex = 1)
points(1:10, AUC_Sim$AUC_15, col = alpha("orange", 0.75), pch = 19, cex = 1)
points(1:10, AUC_Sim$AUC_30, col = alpha("forestgreen", 0.75), pch = 19, cex = 1)
abline(h = 0.5, lty = 3)
axis(side = 1, at = 1:10, labels = metrics_full, las = 2, cex.axis = 1)
legend(x = 7.8, y = 0.25,
       legend = c("Sliding Window = 5 Days", "Sliding Window = 15 Days", "Sliding Window = 30 Days"),
       col = c("red3", "orange", "forestgreen"), pch = 19, bty = "n", y.intersp = 0.5)
```

# Pre-Processed

## Empirical

### Bandwidth = 2

```{r}
AUC_SmoothEmp_2 <- readRDS("Objects/AUC_SmoothEmpiricalData_B2.rds")

par(mar = c(12, 4, 2, 2))
plot(1:10, AUC_SmoothEmp_2$AUC_data, type = "p", 
     main = "Pre-Processed Empirical Data, All Populations | Bandwidth = 2", 
     xaxt = "none", xlab = "", ylim = c(0, 1), ylab = "AUC",
     col = "orchid", pch = 19, cex = 1)
abline(h = 0.5, lty = 3)
axis(side = 1, at = 1:10, labels = metrics_full, las = 2, cex.axis = 1)
```

```{r}
AUC_SmoothEmp_Ex5_2 <- readRDS("Objects/AUC_SmoothEmpiricalData_ExPop5_B2.rds")

par(mar = c(12, 4, 2, 2))
plot(1:10, AUC_SmoothEmp_Ex5_2$AUC_data, type = "p", 
     main = "Pre-Processed Empirical Data, Excluding Pop'n 5 | Bandwidth = 2", 
     xaxt = "none", xlab = "", ylim = c(0, 1), ylab = "AUC",
     col = "orchid", pch = 19, cex = 1)
abline(h = 0.5, lty = 3)
axis(side = 1, at = 1:10, labels = metrics_full, las = 2, cex.axis = 1)
```

### Bandwidth = 3

```{r}
AUC_SmoothEmp_3 <- readRDS("Objects/AUC_SmoothEmpiricalData_B3.rds")

par(mar = c(12, 4, 2, 2))
plot(1:10, AUC_SmoothEmp_3$AUC_data, type = "p", 
     main = "Pre-Processed Empirical Data, All Populations | Bandwidth = 3", 
     xaxt = "none", xlab = "", ylim = c(0, 1), ylab = "AUC",
     col = "orchid", pch = 19, cex = 1)
abline(h = 0.5, lty = 3)
axis(side = 1, at = 1:10, labels = metrics_full, las = 2, cex.axis = 1)
```

```{r}
AUC_SmoothEmp_Ex5_3 <- readRDS("Objects/AUC_SmoothEmpiricalData_ExPop5_B3.rds")

par(mar = c(12, 4, 2, 2))
plot(1:10, AUC_SmoothEmp_Ex5_3$AUC_data, type = "p", 
     main = "Pre-Processed Empirical Data, Excluding Pop'n 5 | Bandwidth = 3", 
     xaxt = "none", xlab = "", ylim = c(0, 1), ylab = "AUC",
     col = "orchid", pch = 19, cex = 1)
abline(h = 0.5, lty = 3)
axis(side = 1, at = 1:10, labels = metrics_full, las = 2, cex.axis = 1)
```

### Bandwidth = 4

```{r}
AUC_SmoothEmp_4 <- readRDS("Objects/AUC_SmoothEmpiricalData_B4.rds")

par(mar = c(12, 4, 2, 2))
plot(1:10, AUC_SmoothEmp_4$AUC_data, type = "p", 
     main = "Pre-Processed Empirical Data, All Populations | Bandwidth = 4", 
     xaxt = "none", xlab = "", ylim = c(0, 1), ylab = "AUC",
     col = "orchid", pch = 19, cex = 1)
abline(h = 0.5, lty = 3)
axis(side = 1, at = 1:10, labels = metrics_full, las = 2, cex.axis = 1)
```

```{r}
AUC_SmoothEmp_Ex5_4 <- readRDS("Objects/AUC_SmoothEmpiricalData_ExPop5_B4.rds")

par(mar = c(12, 4, 2, 2))
plot(1:10, AUC_SmoothEmp_Ex5_4$AUC_data, type = "p", 
     main = "Pre-Processed Empirical Data, Excluding Pop'n 5 | Bandwidth = 4", 
     xaxt = "none", xlab = "", ylim = c(0, 1), ylab = "AUC",
     col = "orchid", pch = 19, cex = 1)
abline(h = 0.5, lty = 3)
axis(side = 1, at = 1:10, labels = metrics_full, las = 2, cex.axis = 1)
```

### Comparison

```{r}
par(mar = c(12, 4, 2, 2))
plot(1:10, AUC_SmoothEmp_2$AUC_data, type = "p", 
     main = "Pre-Processed Empirical Data, All Populations | All Bandwidths", 
     xaxt = "none", xlab = "", ylim = c(0, 1), ylab = "AUC",
     col = alpha("red3", 0.75), pch = 19, cex = 1)
points(1:10, AUC_SmoothEmp_3$AUC_data, col = alpha("orange", 0.75), pch = 19, cex = 1)
points(1:10, AUC_SmoothEmp_4$AUC_data, col = alpha("forestgreen", 0.75), pch = 19, cex = 1)
abline(h = 0.5, lty = 3)
axis(side = 1, at = 1:10, labels = metrics_full, las = 2, cex.axis = 1)
legend(x = 8.5, y = 0.25,
       legend = c("Bandwidth = 2", "Bandwidth = 3", "Bandwidth = 4"),
       col = c("red3", "orange", "forestgreen"), pch = 19, bty = "n", y.intersp = 0.5)

par(mar = c(12, 4, 2, 2))
plot(1:10, AUC_SmoothEmp_Ex5_2$AUC_data, type = "p", 
     main = "Pre-Processed Empirical Data, Excluding Pop'n 5 | All Bandwidths", 
     xaxt = "none", xlab = "", ylim = c(0, 1), ylab = "AUC",
     col = alpha("red3", 0.75), pch = 19, cex = 1)
points(1:10, AUC_SmoothEmp_Ex5_3$AUC_data, col = alpha("orange", 0.75), pch = 19, cex = 1)
points(1:10, AUC_SmoothEmp_Ex5_4$AUC_data, col = alpha("forestgreen", 0.75), pch = 19, cex = 1)
abline(h = 0.5, lty = 3)
axis(side = 1, at = 1:10, labels = metrics_full, las = 2, cex.axis = 1)
legend(x = 8.5, y = 0.25,
       legend = c("Bandwidth = 2", "Bandwidth = 3", "Bandwidth = 4"),
       col = c("red3", "orange", "forestgreen"), pch = 19, bty = "n", y.intersp = 0.5)
```

## Simulated

### Bandwidth = 2

```{r}
AUC_SmoothSim_2 <- readRDS("Objects/AUC_SmoothSimulatedData_B2.rds")

par(mar = c(12, 4, 2, 2))
plot(1:10, AUC_SmoothSim_2$AUC_5, type = "p", 
     main = "Pre-Processed Simulated Data | Bandwidth = 2", 
     xaxt = "none", xlab = "", ylim = c(0, 1), ylab = "AUC",
     col = alpha("red3", 0.75), pch = 19, cex = 1)
points(1:10, AUC_SmoothSim_2$AUC_15, col = alpha("orange", 0.75), pch = 19, cex = 1)
points(1:10, AUC_SmoothSim_2$AUC_30, col = alpha("forestgreen", 0.75), pch = 19, cex = 1)
abline(h = 0.5, lty = 3)
axis(side = 1, at = 1:10, labels = metrics_full, las = 2, cex.axis = 1)
legend(x = 7.8, y = 0.25,
       legend = c("Sliding Window = 5 Days", "Sliding Window = 15 Days", "Sliding Window = 30 Days"),
       col = c("red3", "orange", "forestgreen"), pch = 19, bty = "n", y.intersp = 0.5)
```

### Bandwidth = 3

```{r}
AUC_SmoothSim_3 <- readRDS("Objects/AUC_SmoothSimulatedData_B3.rds")

par(mar = c(12, 4, 2, 2))
plot(1:10, AUC_SmoothSim_3$AUC_5, type = "p", 
     main = "Pre-Processed Simulated Data | Bandwidth = 3", 
     xaxt = "none", xlab = "", ylim = c(0, 1), ylab = "AUC",
     col = alpha("red3", 0.75), pch = 19, cex = 1)
points(1:10, AUC_SmoothSim_3$AUC_15, col = alpha("orange", 0.75), pch = 19, cex = 1)
points(1:10, AUC_SmoothSim_3$AUC_30, col = alpha("forestgreen", 0.75), pch = 19, cex = 1)
abline(h = 0.5, lty = 3)
axis(side = 1, at = 1:10, labels = metrics_full, las = 2, cex.axis = 1)
legend(x = 7.8, y = 0.25,
       legend = c("Sliding Window = 5 Days", "Sliding Window = 15 Days", "Sliding Window = 30 Days"),
       col = c("red3", "orange", "forestgreen"), pch = 19, bty = "n", y.intersp = 0.5)
```

### Bandwidth = 4

```{r}
AUC_SmoothSim_4 <- readRDS("Objects/AUC_SmoothSimulatedData_B4.rds")

par(mar = c(12, 4, 2, 2))
plot(1:10, AUC_SmoothSim_4$AUC_5, type = "p", 
     main = "Pre-Processed Simulated Data | Bandwidth = 4", 
     xaxt = "none", xlab = "", ylim = c(0, 1), ylab = "AUC",
     col = alpha("red3", 0.75), pch = 19, cex = 1)
points(1:10, AUC_SmoothSim_4$AUC_15, col = alpha("orange", 0.75), pch = 19, cex = 1)
points(1:10, AUC_SmoothSim_4$AUC_30, col = alpha("forestgreen", 0.75), pch = 19, cex = 1)
abline(h = 0.5, lty = 3)
axis(side = 1, at = 1:10, labels = metrics_full, las = 2, cex.axis = 1)
legend(x = 7.8, y = 0.25,
       legend = c("Sliding Window = 5 Days", "Sliding Window = 15 Days", "Sliding Window = 30 Days"),
       col = c("red3", "orange", "forestgreen"), pch = 19, bty = "n", y.intersp = 0.5)
```

### Comparison

```{r}
par(mar = c(12, 4, 2, 2))
plot(1:10, AUC_SmoothSim_2$AUC_5, type = "p", 
     main = "Pre-Processed Simulated Data | 5 Day Sliding Window", 
     xaxt = "none", xlab = "", ylim = c(0, 1), ylab = "AUC",
     col = alpha("red3", 0.75), pch = 19, cex = 1)
points(1:10, AUC_SmoothSim_3$AUC_5, col = alpha("orange", 0.75), pch = 19, cex = 1)
points(1:10, AUC_SmoothSim_4$AUC_5, col = alpha("forestgreen", 0.75), pch = 19, cex = 1)
abline(h = 0.5, lty = 3)
axis(side = 1, at = 1:10, labels = metrics_full, las = 2, cex.axis = 1)
legend(x = 8.5, y = 0.25,
       legend = c("Bandwidth = 2", "Bandwidth = 3", "Bandwidth = 4"),
       col = c("red3", "orange", "forestgreen"), pch = 19, bty = "n", y.intersp = 0.5)

par(mar = c(12, 4, 2, 2))
plot(1:10, AUC_SmoothSim_2$AUC_15, type = "p", 
     main = "Pre-Processed Simulated Data | 15 Day Sliding Window", 
     xaxt = "none", xlab = "", ylim = c(0, 1), ylab = "AUC",
     col = alpha("red3", 0.75), pch = 19, cex = 1)
points(1:10, AUC_SmoothSim_3$AUC_15, col = alpha("orange", 0.75), pch = 19, cex = 1)
points(1:10, AUC_SmoothSim_4$AUC_15, col = alpha("forestgreen", 0.75), pch = 19, cex = 1)
abline(h = 0.5, lty = 3)
axis(side = 1, at = 1:10, labels = metrics_full, las = 2, cex.axis = 1)
legend(x = 8.5, y = 0.25,
       legend = c("Bandwidth = 2", "Bandwidth = 3", "Bandwidth = 4"),
       col = c("red3", "orange", "forestgreen"), pch = 19, bty = "n", y.intersp = 0.5)

par(mar = c(12, 4, 2, 2))
plot(1:10, AUC_SmoothSim_2$AUC_30, type = "p", 
     main = "Pre-Processed Simulated Data | 30 Day Sliding Window", 
     xaxt = "none", xlab = "", ylim = c(0, 1), ylab = "AUC",
     col = alpha("red3", 0.75), pch = 19, cex = 1)
points(1:10, AUC_SmoothSim_3$AUC_30, col = alpha("orange", 0.75), pch = 19, cex = 1)
points(1:10, AUC_SmoothSim_4$AUC_30, col = alpha("forestgreen", 0.75), pch = 19, cex = 1)
abline(h = 0.5, lty = 3)
axis(side = 1, at = 1:10, labels = metrics_full, las = 2, cex.axis = 1)
legend(x = 8.5, y = 0.25,
       legend = c("Bandwidth = 2", "Bandwidth = 3", "Bandwidth = 4"),
       col = c("red3", "orange", "forestgreen"), pch = 19, bty = "n", y.intersp = 0.5)
```

# Comparisons

## Objects

```{r}
## Raw
# Empirical
AUC_Emp
AUC_Emp_Ex5
AUC_AdjEmp
AUC_AdjEmp_Ex5
# Simulated
AUC_Sim # (Includes all 3 window sizes)
## Pre-Processed
# Empirical
AUC_SmoothEmp_2
AUC_SmoothEmp_Ex5_2
AUC_SmoothEmp_3
AUC_SmoothEmp_Ex5_3
AUC_SmoothEmp_4
AUC_SmoothEmp_Ex5_4
# Simulated 
AUC_SmoothSim_2 # (Includes all 3 window sizes)
AUC_SmoothSim_3 # (Includes all 3 window sizes)
AUC_SmoothSim_4 # (Includes all 3 window sizes)
```

## Plotting

### Empirical

```{r}
## We're looking at ten versions of this!
v1 <- seq(1, 100, 10); v2 <- seq(2, 100, 10); v3 <- seq(3, 100, 10); v4 <- seq(4, 100, 10); v5 <- seq(5, 100, 10)
v6 <- seq(6, 100, 10); v7 <- seq(7, 100, 10); v8 <- seq(8, 100, 10); v9 <- seq(9, 100, 10); v10 <- seq(10, 100, 10)

par(mar = c(12, 4, 2, 2))
plot(v1, AUC_Emp$AUC_data, type = "p", 
     main = "Empirical Data", 
     # xaxt = "none", 
     xlim = c(2, 99), xlab = "", ylim = c(0, 1), ylab = "AUC",
     col = "red3", pch = 19)
points(v2, AUC_Emp_Ex5$AUC_data, col = "red3", pch = 1)
points(v3, AUC_AdjEmp$AUC_data, col = "goldenrod1", pch = 19)
# points(v4, AUC_AdjEmp_Ex5$AUC_data, col = "goldenrod1", pch = 1)
points(v5, AUC_SmoothEmp_2$AUC_data, col = "springgreen4", pch = 17)
points(v6, AUC_SmoothEmp_Ex5_2$AUC_data, col = "springgreen4", pch = 2)
points(v7, AUC_SmoothEmp_3$AUC_data, col = "navy", pch = 17)
points(v8, AUC_SmoothEmp_Ex5_3$AUC_data, col = "navy", pch = 2)
points(v9, AUC_SmoothEmp_4$AUC_data, col = "orchid", pch = 17)
points(v10, AUC_SmoothEmp_Ex5_4$AUC_data, col = "orchid", pch = 2)
abline(v = c(10.5, 20.5, 30.5, 40.5, 50.5, 60.5, 70.5, 80.5, 90.5), lty = 3, col = "grey")
abline(h = 0.5, lty = 3, col = "black")
axis(side = 1, at = seq(5.5, 100, 10), labels = metrics_full, las = 2, cex.axis = 1)
legend(x = 75, y = 0.28, 
       legend = c("Raw", "Adjusted", "Smoothed (Bandwidth = 2)", "Smoothed (Bandwidth = 3)", "Smoothed (Bandwidth = 4)"), 
       col = c("red3", "goldenrod1", "springgreen4", "navy", "orchid"), pch = c(19, 19, 17, 17, 17),
       box.lwd = 0, box.col = "white", bg = "white", y.intersp = 0.3)
```

### Simulated

```{r}
v1 <- seq(1, 40, 4); v2 <- seq(2, 40, 4); v3 <- seq(3, 40, 4); v4 <- seq(4, 40, 4)

par(mar = c(12, 4, 2, 2))
plot(v1, AUC_Sim$AUC_15, type = "p", 
     main = "Simulated Data", 
     xlim = c(2, 39), xlab = "", ylim = c(0, 1), ylab = "AUC",
     col = "red3", pch = 19)
points(v2, AUC_SmoothSim_2$AUC_15, col = "orange", pch = 19)
points(v3, AUC_SmoothSim_3$AUC_15, col = "springgreen4", pch = 19)
points(v4, AUC_SmoothSim_4$AUC_15, col = "orchid", pch = 19)
abline(v = c(4.5, 8.5, 12.5, 16.5, 20.5, 24.5, 28.5, 32.5, 36.5), lty = 3, col = "grey")
abline(h = 0.5, lty = 3, col = "black")
axis(side = 1, at = seq(2.5, 40, 4), labels = metrics_full, las = 2, cex.axis = 1)
legend(x = 33, y = 0.25, 
       legend = c("Raw", "Smoothed (Bandwidth = 2)", "Smoothed (Bandwidth = 3)", "Smoothed (Bandwidth = 4)"), 
       col = c("red3", "orange", "springgreen4", "orchid"), pch = 19,
       box.lwd = 0, box.col = "white", bg = "white", y.intersp = 0.3)
```

Note: To generate these objects, run `8_EWS-ByPop.Rmd`.

```{r}
metric <- c(rep(1, 10), rep(2, 10), rep(3, 10), rep(4, 10), rep(5, 10),
            rep(6, 10), rep(7, 10), rep(8, 10), rep(9, 10), rep(10, 10))
raw_df <- data.frame(cbind(metric, raw_aucs))

raw_df$metric <- as.factor(raw_df$metric)
ggplot(raw_df, aes(x = metric, y = raw_aucs, colour = metric)) + 
  geom_boxplot() +
  geom_jitter(shape = 16, position = position_jitter(0.2)) +
  geom_hline(yintercept = 0.5, colour = "grey", linetype = "dotted") +
  theme(panel.background = element_blank(),
        plot.title = element_text(size = 18),
        axis.title = element_text(size = 16),
        axis.text.x = element_text(color = "black", size = 12, angle = 30, vjust = 0.8, hjust = 0.8),
        axis.text.y = element_text(color = "black", size = 12),
        legend.position = "none") +
  labs(title = "Raw Simulated Data | 15 Day Sliding Window", x = "", y = "AUC") +
  scale_x_discrete(labels = metrics_full) +
  ylim(0, 1)

smooth_df <- data.frame(cbind(metric, smooth_3_aucs))

smooth_df$metric <- as.factor(smooth_df$metric)
ggplot(smooth_df, aes(x = metric, y = smooth_3_aucs, colour = metric)) + 
  geom_boxplot() +
  geom_jitter(shape = 16, position = position_jitter(0.2)) +
  geom_hline(yintercept = 0.5, colour = "grey", linetype = "dotted") +
  theme(panel.background = element_blank(),
        plot.title = element_text(size = 18),
        axis.title = element_text(size = 16),
        axis.text.x = element_text(color = "black", size = 12, angle = 30, vjust = 0.8, hjust = 0.8),
        axis.text.y = element_text(color = "black", size = 12),
        legend.position = "none") +
  labs(title = "Pre-Processed Simulated Data (Bandwidth = 3) | 15 Day Sliding Window", x = "", y = "AUC") +
  labs(x = "", y = "AUC") +
  scale_x_discrete(labels = metrics_full) +
  ylim(0, 1)
```

# BY POPULATION

# Raw, Simulated

```{r}
cols <- c(rep("#1434A4", 512), rep("#C21E56", 512))
cols.pt <- c(rep("#A7C7E7", 1000), rep("#F6799D", 1000))
```

```{r}
## Mean
raw.sim.mean.15.tau <- readRDS("Objects/raw.sim.mean.15.tau.rds")
med.const.sims.mean.15.tau <- median(constant.sims.mean.15.tau)
med.warm.sims.mean.15.tau <- median(warming.sims.mean.15.tau)
dens <- ggplot(data = raw.sim.mean.15.tau, aes(x = k.tau, group = Treatment, fill = Treatment)) +
  geom_density(alpha = 0.4, colour = cols) +
  scale_fill_manual(values = c("#1434A4", "#C21E56")) +
  geom_vline(xintercept = med.const.sims.mean.15.tau, colour = "#1434A4") +
  geom_vline(xintercept = med.warm.sims.mean.15.tau, colour = "#C21E56") +
  xlab("Kendall's Tau") +
  ylab("Density (Mean)") +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"))
violin <- ggplot(raw.sim.mean.15.tau, aes(x = treatment, y = k.tau)) + 
  geom_violin(fill = cols, colour = cols) +
  geom_jitter(height = 0, width = 0.2, colour = cols.pt) +
  stat_summary(fun.y = median, geom = "point", size = 6, colour = "black", shape = 18) + 
  xlab("Mean") +
  ylab("Kendall's Tau") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, colour = "black"),
        text = element_text(size = 12)) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"))
plot_grid(dens, violin, align = "h", labels = "AUTO")

## Variance
raw.sim.variance.15.tau <- readRDS("Objects/raw.sim.variance.15.tau.rds")
med.const.sims.variance.15.tau <- median(constant.sims.variance.15.tau)
med.warm.sims.variance.15.tau <- median(warming.sims.variance.15.tau)
dens <- ggplot(data = raw.sim.variance.15.tau, aes(x = k.tau, group = Treatment, fill = Treatment)) +
  geom_density(alpha = 0.4, colour = cols) +
  scale_fill_manual(values = c("#1434A4", "#C21E56")) +
  geom_vline(xintercept = med.const.sims.variance.15.tau, colour = "#1434A4") +
  geom_vline(xintercept = med.warm.sims.variance.15.tau, colour = "#C21E56") +
  xlab("Kendall's Tau") +
  ylab("Density (Variance)") +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"))
violin <- ggplot(raw.sim.variance.15.tau, aes(x = treatment, y = k.tau)) + 
  geom_violin(fill = cols, colour = cols) +
  geom_jitter(height = 0, width = 0.2, colour = cols.pt) +
  stat_summary(fun.y = median, geom = "point", size = 6, colour = "black", shape = 18) + 
  xlab("Variance") +
  ylab("Kendall's Tau") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, colour = "black"),
        text = element_text(size = 12)) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"))
plot_grid(dens, violin, align = "h", labels = "AUTO")

## Skewness
raw.sim.skewness.15.tau <- readRDS("Objects/raw.sim.skewness.15.tau.rds")
med.const.sims.skewness.15.tau <- median(constant.sims.skewness.15.tau)
med.warm.sims.skewness.15.tau <- median(warming.sims.skewness.15.tau)
dens <- ggplot(data = raw.sim.skewness.15.tau, aes(x = k.tau, group = Treatment, fill = Treatment)) +
  geom_density(alpha = 0.4, colour = cols) +
  scale_fill_manual(values = c("#1434A4", "#C21E56")) +
  geom_vline(xintercept = med.const.sims.skewness.15.tau, colour = "#1434A4") +
  geom_vline(xintercept = med.warm.sims.skewness.15.tau, colour = "#C21E56") +
  xlab("Kendall's Tau") +
  ylab("Density (Skewness)") +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"))
violin <- ggplot(raw.sim.skewness.15.tau, aes(x = treatment, y = k.tau)) + 
  geom_violin(fill = cols, colour = cols) +
  geom_jitter(height = 0, width = 0.2, colour = cols.pt) +
  stat_summary(fun.y = median, geom = "point", size = 6, colour = "black", shape = 18) + 
  xlab("Skewness") +
  ylab("Kendall's Tau") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, colour = "black"),
        text = element_text(size = 12)) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"))
plot_grid(dens, violin, align = "h", labels = "AUTO")

## Kurtosis
raw.sim.kurtosis.15.tau <- readRDS("Objects/raw.sim.kurtosis.15.tau.rds")
med.const.sims.kurtosis.15.tau <- median(constant.sims.kurtosis.15.tau)
med.warm.sims.kurtosis.15.tau <- median(warming.sims.kurtosis.15.tau)
dens <- ggplot(data = raw.sim.kurtosis.15.tau, aes(x = k.tau, group = Treatment, fill = Treatment)) +
  geom_density(alpha = 0.4, colour = cols) +
  scale_fill_manual(values = c("#1434A4", "#C21E56")) +
  geom_vline(xintercept = med.const.sims.kurtosis.15.tau, colour = "#1434A4") +
  geom_vline(xintercept = med.warm.sims.kurtosis.15.tau, colour = "#C21E56") +
  xlab("Kendall's Tau") +
  ylab("Density (Kurtosis)") +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"))
violin <- ggplot(raw.sim.kurtosis.15.tau, aes(x = treatment, y = k.tau)) + 
  geom_violin(fill = cols, colour = cols) +
  geom_jitter(height = 0, width = 0.2, colour = cols.pt) +
  stat_summary(fun.y = median, geom = "point", size = 6, colour = "black", shape = 18) + 
  xlab("Kurtosis") +
  ylab("Kendall's Tau") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, colour = "black"),
        text = element_text(size = 12)) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"))
plot_grid(dens, violin, align = "h", labels = "AUTO")

## Co-Efficient of Variation
raw.sim.cv.15.tau <- readRDS("Objects/raw.sim.cv.15.tau.rds")
med.const.sims.cv.15.tau <- median(constant.sims.cv.15.tau)
med.warm.sims.cv.15.tau <- median(warming.sims.cv.15.tau)
dens <- ggplot(data = raw.sim.cv.15.tau, aes(x = k.tau, group = Treatment, fill = Treatment)) +
  geom_density(alpha = 0.4, colour = cols) +
  scale_fill_manual(values = c("#1434A4", "#C21E56")) +
  geom_vline(xintercept = med.const.sims.cv.15.tau, colour = "#1434A4") +
  geom_vline(xintercept = med.warm.sims.cv.15.tau, colour = "#C21E56") +
  xlab("Kendall's Tau") +
  ylab("Density (Co-Efficient of Variation)") +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"))
violin <- ggplot(raw.sim.cv.15.tau, aes(x = treatment, y = k.tau)) + 
  geom_violin(fill = cols, colour = cols) +
  geom_jitter(height = 0, width = 0.2, colour = cols.pt) +
  stat_summary(fun.y = median, geom = "point", size = 6, colour = "black", shape = 18) + 
  xlab("Co-Efficient of Variation") +
  ylab("Kendall's Tau") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, colour = "black"),
        text = element_text(size = 12)) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"))
plot_grid(dens, violin, align = "h", labels = "AUTO")

## Index of Dispersion
raw.sim.id.15.tau <- readRDS("Objects/raw.sim.id.15.tau.rds")
med.const.sims.id.15.tau <- median(constant.sims.id.15.tau)
med.warm.sims.id.15.tau <- median(warming.sims.id.15.tau)
dens <- ggplot(data = raw.sim.id.15.tau, aes(x = k.tau, group = Treatment, fill = Treatment)) +
  geom_density(alpha = 0.4, colour = cols) +
  scale_fill_manual(values = c("#1434A4", "#C21E56")) +
  geom_vline(xintercept = med.const.sims.id.15.tau, colour = "#1434A4") +
  geom_vline(xintercept = med.warm.sims.id.15.tau, colour = "#C21E56") +
  xlab("Kendall's Tau") +
  ylab("Density (Index of Dispersion)") +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"))
violin <- ggplot(raw.sim.id.15.tau, aes(x = treatment, y = k.tau)) + 
  geom_violin(fill = cols, colour = cols) +
  geom_jitter(height = 0, width = 0.2, colour = cols.pt) +
  stat_summary(fun.y = median, geom = "point", size = 6, colour = "black", shape = 18) + 
  xlab("Index of Dispersion") +
  ylab("Kendall's Tau") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, colour = "black"),
        text = element_text(size = 12)) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"))
plot_grid(dens, violin, align = "h", labels = "AUTO")

## First Difference Variance
raw.sim.first.diff.variance.15.tau <- readRDS("Objects/raw.sim.first.diff.variance.15.tau.rds")
med.const.sims.first.diff.variance.15.tau <- median(constant.sims.first.diff.variance.15.tau)
med.warm.sims.first.diff.variance.15.tau <- median(warming.sims.first.diff.variance.15.tau)
dens <- ggplot(data = raw.sim.first.diff.variance.15.tau, aes(x = k.tau, group = Treatment, fill = Treatment)) +
  geom_density(alpha = 0.4, colour = cols) +
  scale_fill_manual(values = c("#1434A4", "#C21E56")) +
  geom_vline(xintercept = med.const.sims.first.diff.variance.15.tau, colour = "#1434A4") +
  geom_vline(xintercept = med.warm.sims.first.diff.variance.15.tau, colour = "#C21E56") +
  xlab("Kendall's Tau") +
  ylab("Density (First Difference Variance)") +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"))
violin <- ggplot(raw.sim.first.diff.variance.15.tau, aes(x = treatment, y = k.tau)) + 
  geom_violin(fill = cols, colour = cols) +
  geom_jitter(height = 0, width = 0.2, colour = cols.pt) +
  stat_summary(fun.y = median, geom = "point", size = 6, colour = "black", shape = 18) + 
  xlab("First Difference Variance") +
  ylab("Kendall's Tau") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, colour = "black"),
        text = element_text(size = 12)) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"))
plot_grid(dens, violin, align = "h", labels = "AUTO")

## Autocorrelation
raw.sim.cor.15.tau <- readRDS("Objects/raw.sim.cor.15.tau.rds")
med.const.sims.cor.15.tau <- median(constant.sims.cor.15.tau)
med.warm.sims.cor.15.tau <- median(warming.sims.cor.15.tau)
dens <- ggplot(data = raw.sim.cor.15.tau, aes(x = k.tau, group = Treatment, fill = Treatment)) +
  geom_density(alpha = 0.4, colour = cols) +
  scale_fill_manual(values = c("#1434A4", "#C21E56")) +
  geom_vline(xintercept = med.const.sims.cor.15.tau, colour = "#1434A4") +
  geom_vline(xintercept = med.warm.sims.cor.15.tau, colour = "#C21E56") +
  xlab("Kendall's Tau") +
  ylab("Density (Autocorrelation)") +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"))
violin <- ggplot(raw.sim.cor.15.tau, aes(x = treatment, y = k.tau)) + 
  geom_violin(fill = cols, colour = cols) +
  geom_jitter(height = 0, width = 0.2, colour = cols.pt) +
  stat_summary(fun.y = median, geom = "point", size = 6, colour = "black", shape = 18) + 
  xlab("Autocorrelation") +
  ylab("Kendall's Tau") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, colour = "black"),
        text = element_text(size = 12)) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"))
plot_grid(dens, violin, align = "h", labels = "AUTO")

## Autocovariance
raw.sim.cov.15.tau <- readRDS("Objects/raw.sim.cov.15.tau.rds")
med.const.sims.cov.15.tau <- median(constant.sims.cov.15.tau)
med.warm.sims.cov.15.tau <- median(warming.sims.cov.15.tau)
dens <- ggplot(data = raw.sim.cov.15.tau, aes(x = k.tau, group = Treatment, fill = Treatment)) +
  geom_density(alpha = 0.4, colour = cols) +
  scale_fill_manual(values = c("#1434A4", "#C21E56")) +
  geom_vline(xintercept = med.const.sims.cov.15.tau, colour = "#1434A4") +
  geom_vline(xintercept = med.warm.sims.cov.15.tau, colour = "#C21E56") +
  xlab("Kendall's Tau") +
  ylab("Density (Autocovariance)") +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"))
violin <- ggplot(raw.sim.cov.15.tau, aes(x = treatment, y = k.tau)) + 
  geom_violin(fill = cols, colour = cols) +
  geom_jitter(height = 0, width = 0.2, colour = cols.pt) +
  stat_summary(fun.y = median, geom = "point", size = 6, colour = "black", shape = 18) + 
  xlab("Autocovariance") +
  ylab("Kendall's Tau") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, colour = "black"),
        text = element_text(size = 12)) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"))
plot_grid(dens, violin, align = "h", labels = "AUTO")

## Decay Time
raw.sim.decay.time.15.tau <- readRDS("Objects/raw.sim.decay.time.15.tau.rds")
med.const.sims.decay.time.15.tau <- median(constant.sims.decay.time.15.tau)
med.warm.sims.decay.time.15.tau <- median(warming.sims.decay.time.15.tau)
dens <- ggplot(data = raw.sim.decay.time.15.tau, aes(x = k.tau, group = Treatment, fill = Treatment)) +
  geom_density(alpha = 0.4, colour = cols) +
  scale_fill_manual(values = c("#1434A4", "#C21E56")) +
  geom_vline(xintercept = med.const.sims.decay.time.15.tau, colour = "#1434A4") +
  geom_vline(xintercept = med.warm.sims.decay.time.15.tau, colour = "#C21E56") +
  xlab("Kendall's Tau") +
  ylab("Density (Decay Time)") +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"))
violin <- ggplot(raw.sim.decay.time.15.tau, aes(x = treatment, y = k.tau)) + 
  geom_violin(fill = cols, colour = cols) +
  geom_jitter(height = 0, width = 0.2, colour = cols.pt) +
  stat_summary(fun.y = median, geom = "point", size = 6, colour = "black", shape = 18) + 
  xlab("Decay Time") +
  ylab("Kendall's Tau") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, colour = "black"),
        text = element_text(size = 12)) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"))
plot_grid(dens, violin, align = "h", labels = "AUTO")
```

# Raw, Empirical
